import socket
s = socket.socket()
print("Socket Successfully Created \n")
hostname = socket.gethostname()
print(hostname)
s.bind((hostname , 9999))
s.listen(1)
print("Waiting for the incoming Connections")
c,addr = s.accept()
print(addr , "connected with the server.")
filename = input(str("please enter the filename u want to send :"))
file = open(filename , 'rb')
file_data = file.read(1024)
c.send(file_data)
print("Data has been transmitted successfully")